### ISSUE TITLE
Adding a ByteArrayOutputStream as addAdditionalData to the UninstallData fails when serializing

### ISSUE THREAD

**Issue by reinhapa** [izpack/izpack.github.com#21]
When adding an `java.io.ByteArrayOutputStream` object to the `com.izforge.izpack.installer.data.UninstallData`, `com.izforge.izpack.installer.data.UninstallDataWriter.write()` fails with a `ClassCastException` due to a premature cast within the `writeAdditionalUninstallData()` method.

```
SEVERE: java.io.ByteArrayOutputStream cannot be cast to java.io.Serializable
java.lang.ClassCastException: java.io.ByteArrayOutputStream cannot be cast to java.io.Serializable
        at com.izforge.izpack.installer.data.UninstallDataWriter.writeAdditionalUninstallData(UninstallDataWriter.java:399)
        at com.izforge.izpack.installer.data.UninstallDataWriter.write(UninstallDataWriter.java:123)
        at com.izforge.izpack.installer.gui.InstallerFrame.writeUninstallData(InstallerFrame.java:1402)
        at com.izforge.izpack.installer.gui.InstallerFrame.quit(InstallerFrame.java:659)
        at com.izforge.izpack.installer.gui.DefaultNavigator.quit(DefaultNavigator.java:387)
        at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler.navigate(DefaultNavigator.java:563)
        at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler.access$100(DefaultNavigator.java:522)
        at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler$1$1.run(DefaultNavigator.java:542)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by reinhapa** [comment]
Wrong project
